//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonuForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int k_id { get; set; }
        public string k_ad { get; set; }
        public string k_yazar { get; set; }
        public string k_kategori { get; set; }
    }
}
